[workspace]
members = ["benchmarks", "cli", "console"]

[workspace.dependencies]
datafusion = { git = "https://github.com/apache/datafusion", branch = "branch-53", default-features = false }
datafusion-proto = { git = "https://github.com/apache/datafusion", branch = "branch-53" }

[package]
name = "datafusion-distributed"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44" }
datafusion = { workspace = true, features = [
  "parquet",
  "sql",
  "unicode_expressions",
  "datetime_expressions",
] }
datafusion-proto = { workspace = true }
arrow-flight = "58"
arrow-select = "58"
arrow-ipc = { version = "58", features = ["zstd"] }
async-trait = "0.1.89"
tokio = { version = "1.48", features = ["full"] }
tonic = { version = "0.14.1", features = ["transport"] }
tower = "0.5.2"
http = "1.3.1"
itertools = "0.14.0"
futures = "0.3.31"
url = "2.5.7"
uuid = "1.19"
delegate = "0.13.4"
dashmap = "6.0.1"
prost = "0.14.1"
rand = "0.9"
object_store = "0.13"
bytes = "1.11"
pin-project = "1.1.10"
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-util = "0.7"
moka = { version = "0.12", features = ["sync", "future"] }
crossbeam-queue = "0.3"
sysinfo = { version = "0.30", optional = true }
sketches-ddsketch = { version = "0.3", features = ["use_serde"] }
bincode = "1"

# integration_tests deps
insta = { version = "1.46.0", features = ["filters"], optional = true }
tpchgen = { git = "https://github.com/clflushopt/tpchgen-rs", rev = "438e9c2dbc25b2fff82c0efc08b3f13b5707874f", optional = true }
tpchgen-arrow = { git = "https://github.com/clflushopt/tpchgen-rs", rev = "438e9c2dbc25b2fff82c0efc08b3f13b5707874f", optional = true }
parquet = { version = "58", optional = true }
arrow = { version = "58", optional = true, features = ["test_utils"] }
hyper-util = { version = "0.1.16", optional = true }
pretty_assertions = { version = "1.4", optional = true }
reqwest = { version = "0.12", optional = true }
zip = { version = "6.0", optional = true }
tonic-prost = "0.14.2"

[features]
avro = ["datafusion/avro"]
integration = [
  "insta",
  "tpchgen",
  "tpchgen-arrow",
  "parquet",
  "arrow",
  "hyper-util",
  "pretty_assertions",
  "reqwest",
  "zip",
]

system-metrics = ["sysinfo"]

tpch = ["integration"]
tpcds = ["integration"]
clickbench = ["integration"]
sysinfo = ["dep:sysinfo"]
insta = ["dep:insta"]

[dev-dependencies]
structopt = "0.3"
insta = { version = "1.46.0", features = ["filters"] }
tpchgen = { git = "https://github.com/clflushopt/tpchgen-rs", rev = "438e9c2dbc25b2fff82c0efc08b3f13b5707874f" }
tpchgen-arrow = { git = "https://github.com/clflushopt/tpchgen-rs", rev = "438e9c2dbc25b2fff82c0efc08b3f13b5707874f" }
parquet = "58"
arrow = { version = "58", features = ["test_utils"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
hyper-util = "0.1.16"
pretty_assertions = "1.4"
reqwest = "0.12"
zip = "6.0"
test-case = "3.3.1"
